name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: * */8 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EAI_SESS: ${{ secrets.EAI_SESS }}
          ACCOUNT: ${{ secrets.ACCOUNTPHD }}
          PASSWORD: ${{ secrets.PASSWORDPHD }}
          EAI_SESS: ${{ secrets.EAI_SESSPHD }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD} ${EAI_SESS}
          python3 clock-in.py ${ACCOUNTPHD} ${PASSWORDPHD} ${EAI_SESSPHD}
